### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by bhunt02** [Bawnorton/Bamboozlers#19]
# Milestone 2 (Due February 16, 11:59 p.m.)
Create a PDF report for Milestone 2 and make repository adjustments to accompany it.

### Check List
- [ ] Complete requirements elicitation phase.
- [ ] Create a PDF report for Milestone 2 via a collaborative document editing application.
- [ ] Add the following to the PDF report:
  - [ ] What the project is
  - [ ] A high-level description of what the project will offer. Must adequately detail a summary of what it will do.
  - [ ] User Requirements for the system
  - [ ] Functional Requirements for the system
  - [ ] Non-functional Requirements for the system
  - [ ] Use Case UML Diagrams with the proper level of detail describing the specific scenarios (Must include diagram + detailed text)
- [ ] #8
- [ ] Update project-level README.md to include the details of the requirements.

### Notes
* Check list is subject to change.
